# Falls back to 'core-service' if env variable is missing
spring.application.name=${APP_NAME:core-service}

# Spring Security
spring.security.user.name=${APP_USERNAME}
spring.security.user.password=${APP_PASSWORD}

# Database Config (Falls back to your local JustifAI DB credentials)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

server.port=${SERVER_PORT}
spring.jackson.time-zone=${APP_TIMEZONE}

# ML Service Routing (Falls back to localhost Python server)
justifai.ml-service.url=${ML_SERVICE_URL:http://localhost:8000/api/v1}

# API Version Routing
justifai.api.base-path=/api/v1

# CORS Configuration (Falls back to local Angular server)
justifai.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}